// Copyright 2026 Slick Quant
// SPDX-License-Identifier: MIT

// Generated by CMake from cmake/version.hpp.in - do not edit.
// The version is defined by project(VERSION) in CMakeLists.txt.

#pragma once

#define SLICK_ORDERBOOK_VERSION_MAJOR 1
#define SLICK_ORDERBOOK_VERSION_MINOR 0
#define SLICK_ORDERBOOK_VERSION_PATCH 5
#define SLICK_ORDERBOOK_VERSION_STRING "1.0.5"
