Slick OrderBook: slick::orderbook::OrderBookL2 Class Reference
slick::orderbook::OrderBookL2 Class Reference
Level 2 OrderBook - aggregated price levels.
#include <orderbook_l2.hpp>
Public Member Functions
OrderBookL2 (SymbolId symbol, std::size_t initial_capacity=32)
Constructor.
~OrderBookL2 ()=default
Destructor.
OrderBookL2 (const OrderBookL2 &)=delete
OrderBookL2 & operator= (const OrderBookL2 &)=delete
OrderBookL2 (OrderBookL2 &&) noexcept
OrderBookL2 & operator= (OrderBookL2 &&) noexcept
SymbolId symbol () const noexcept
Get symbol ID.
void updateLevel (Side side, Price price, Quantity quantity, Timestamp timestamp, uint64_t seq_num=0, bool is_last_in_batch=true)
Add or update a price level If quantity is 0, the level is deleted.
bool deleteLevel (Side side, Price price) noexcept
Delete a price level.
void clearSide (Side side) noexcept
Clear all levels on one side.
void clear () noexcept
Clear all levels (both sides)
const detail::PriceLevelL2 * getBestBid () const noexcept
Get best bid (highest buy price)
const detail::PriceLevelL2 * getBestAsk () const noexcept
Get best ask (lowest sell price)
TopOfBook getTopOfBook () const noexcept
Get top-of-book snapshot.
std::vector< detail::PriceLevelL2 > getLevels (Side side, std::size_t depth=0) const
Get price levels for a side.
const detail::PriceLevelL2 * getLevel (Side side, Price price) const noexcept
Get a specific price level by price.
const detail::PriceLevelL2 * getLevelByIndex (Side side, uint16_t index) const noexcept
Get a price level by index (0 = best)
std::size_t levelCount (Side side) const noexcept
Get number of levels on a side.
bool isEmpty (Side side) const noexcept
Check if a side is empty.
bool isEmpty () const noexcept
Check if book is empty (both sides)
void addObserver (std::shared_ptr< IOrderBookObserver > observer)
Observer management.
bool removeObserver (const std::shared_ptr< IOrderBookObserver > &observer)
void clearObservers () noexcept
std::size_t observerCount () const noexcept
uint64_t getLastSeqNum () const noexcept
Get last processed sequence number.
void emitSnapshot (Timestamp timestamp)
Emit complete orderbook snapshot to observers Useful for replaying full book state to a new observer Calls onSnapshotBegin(), followed by onPriceLevelUpdate() for each level, then onSnapshotEnd()
Detailed Description
Level 2 OrderBook - aggregated price levels.
Maintains aggregated order book state with price levels and total quantities. Does not track individual orders.
Features:
O(log n) updates (binary search in sorted vector)
O(1) best bid/ask queries
Cache-friendly memory layout
Observer pattern for notifications
Thread Safety: Single writer, multiple readers (lock-free reads planned)
Memory Layout: Cache-aligned to 64 bytes for optimal performance
Usage:
OrderBookL2 book(symbol_id);
book.updateLevel(Side::Buy, 10000, 100, timestamp);
auto best_bid = book.getBestBid();
Definition at line 40 of file orderbook_l2.hpp.
Constructor & Destructor Documentation
OrderBookL2() [1/3]
slick::orderbook::OrderBookL2::OrderBookL2 (SymbolId symbol, std::size_t initial_capacity = 32) inline explicit
Constructor.
Parameters
symbol Symbol identifier
initial_capacity Initial capacity for price levels per side
Definition at line 12 of file orderbook_l2_impl.hpp.
References slick::orderbook::Buy, and slick::orderbook::Sell.
~OrderBookL2()
slick::orderbook::OrderBookL2::~OrderBookL2 () default
Destructor.
OrderBookL2() [2/3]
slick::orderbook::OrderBookL2::OrderBookL2 (const OrderBookL2 &) delete
OrderBookL2() [3/3]
slick::orderbook::OrderBookL2::OrderBookL2 (OrderBookL2 && other) inline noexcept
Definition at line 27 of file orderbook_l2_impl.hpp.
Member Function Documentation
addObserver()
void slick::orderbook::OrderBookL2::addObserver (std::shared_ptr< IOrderBookObserver > observer) inline
Observer management.
Definition at line 130 of file orderbook_l2.hpp.
clear()
void slick::orderbook::OrderBookL2::clear () inline noexcept
Clear all levels (both sides)
Definition at line 121 of file orderbook_l2_impl.hpp.
References slick::orderbook::Buy, and slick::orderbook::Sell.
clearObservers()
void slick::orderbook::OrderBookL2::clearObservers () inline noexcept
Definition at line 138 of file orderbook_l2.hpp.
clearSide()
void slick::orderbook::OrderBookL2::clearSide (Side side) inline noexcept
Clear all levels on one side.
Parameters
side Buy or Sell
Definition at line 116 of file orderbook_l2_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
deleteLevel()
bool slick::orderbook::OrderBookL2::deleteLevel (Side side, Price price) inline noexcept
Delete a price level.
Parameters
side Buy or Sell
price Price level to delete
Returns
true if level was found and deleted
Definition at line 111 of file orderbook_l2_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
emitSnapshot()
void slick::orderbook::OrderBookL2::emitSnapshot (Timestamp timestamp) inline
Emit complete orderbook snapshot to observers Useful for replaying full book state to a new observer Calls onSnapshotBegin(), followed by onPriceLevelUpdate() for each level, then onSnapshotEnd()
Parameters
timestamp Snapshot timestamp
Definition at line 225 of file orderbook_l2_impl.hpp.
References slick::orderbook::Buy, slick::orderbook::ObserverManager::notifyPriceLevelUpdate(), slick::orderbook::ObserverManager::notifySnapshotBegin(), slick::orderbook::ObserverManager::notifySnapshotEnd(), slick::orderbook::PriceChanged, slick::orderbook::QuantityChanged, and slick::orderbook::Sell.
getBestAsk()
const detail::PriceLevelL2 * slick::orderbook::OrderBookL2::getBestAsk () const inline noexcept
Get best ask (lowest sell price)
Returns
Pointer to best ask level, or nullptr if no asks
Definition at line 130 of file orderbook_l2_impl.hpp.
References slick::orderbook::Sell.
getBestBid()
const detail::PriceLevelL2 * slick::orderbook::OrderBookL2::getBestBid () const inline noexcept
Get best bid (highest buy price)
Returns
Pointer to best bid level, or nullptr if no bids
Definition at line 126 of file orderbook_l2_impl.hpp.
References slick::orderbook::Buy.
getLastSeqNum()
uint64_t slick::orderbook::OrderBookL2::getLastSeqNum () const inline noexcept
Get last processed sequence number.
Returns
Last sequence number (0 if not tracking)
Definition at line 148 of file orderbook_l2.hpp.
getLevel()
const detail::PriceLevelL2 * slick::orderbook::OrderBookL2::getLevel (Side side, Price price) const inline noexcept
Get a specific price level by price.
Parameters
side Buy or Sell
price Price to look up
Returns
Pointer to price level, or nullptr if not found
Definition at line 157 of file orderbook_l2_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
getLevelByIndex()
const detail::PriceLevelL2 * slick::orderbook::OrderBookL2::getLevelByIndex (Side side, uint16_t index) const inline noexcept
Get a price level by index (0 = best)
Parameters
side Buy or Sell
index Level index (0-based, 0 = best bid/ask)
Returns
Pointer to price level, or nullptr if index out of range
Definition at line 162 of file orderbook_l2_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
getLevels()
std::vector< detail::PriceLevelL2 > slick::orderbook::OrderBookL2::getLevels (Side side, std::size_t depth = 0) const inline
Get price levels for a side.
Parameters
side Buy or Sell
depth Maximum number of levels (0 = all)
Returns
Vector of price levels
Definition at line 152 of file orderbook_l2_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
getTopOfBook()
TopOfBook slick::orderbook::OrderBookL2::getTopOfBook () const inline noexcept
Get top-of-book snapshot.
Returns
TopOfBook structure with best bid/ask
Definition at line 134 of file orderbook_l2_impl.hpp.
isEmpty() [1/2]
bool slick::orderbook::OrderBookL2::isEmpty () const inline noexcept
Check if book is empty (both sides)
Returns
true if both sides are empty
Definition at line 181 of file orderbook_l2_impl.hpp.
References slick::orderbook::Buy, and slick::orderbook::Sell.
isEmpty() [2/2]
bool slick::orderbook::OrderBookL2::isEmpty (Side side) const inline noexcept
Check if a side is empty.
Parameters
side Buy or Sell
Returns
true if side has no levels
Definition at line 176 of file orderbook_l2_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
levelCount()
std::size_t slick::orderbook::OrderBookL2::levelCount (Side side) const inline noexcept
Get number of levels on a side.
Parameters
side Buy or Sell
Returns
Number of levels
Definition at line 171 of file orderbook_l2_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
observerCount()
std::size_t slick::orderbook::OrderBookL2::observerCount () const inline noexcept
Definition at line 142 of file orderbook_l2.hpp.
operator=() [1/2]
OrderBookL2 & slick::orderbook::OrderBookL2::operator= (const OrderBookL2 &) delete
operator=() [2/2]
OrderBookL2 & slick::orderbook::OrderBookL2::operator= (OrderBookL2 && other) inline noexcept
Definition at line 37 of file orderbook_l2_impl.hpp.
removeObserver()
bool slick::orderbook::OrderBookL2::removeObserver (const std::shared_ptr< IOrderBookObserver > & observer) inline
Definition at line 134 of file orderbook_l2.hpp.
symbol()
SymbolId slick::orderbook::OrderBookL2::symbol () const inline noexcept
Get symbol ID.
Definition at line 57 of file orderbook_l2.hpp.
updateLevel()
void slick::orderbook::OrderBookL2::updateLevel (Side side, Price price, Quantity quantity, Timestamp timestamp, uint64_t seq_num = 0, bool is_last_in_batch = true) inline
Add or update a price level If quantity is 0, the level is deleted.
Parameters
side Buy or Sell
price Price level
quantity Total quantity at this level (0 = delete)
timestamp Update timestamp
seq_num Exchange sequence number (0 = no tracking, default) Out-of-order updates (seq_num <= last_seq_num) are rejected
is_last_in_batch Set to true if this is the last update in an external batch (enables batching of TopOfBook updates)
Definition at line 49 of file orderbook_l2_impl.hpp.
References slick::orderbook::LastInBatch, slick::orderbook::ObserverManager::notifyPriceLevelUpdate(), slick::orderbook::PriceChanged, slick::orderbook::QuantityChanged, slick::orderbook::SideCount, and SLICK_ASSERT.
The documentation for this class was generated from the following files:
slick/orderbook/orderbook_l2.hpp
slick/orderbook/detail/impl/orderbook_l2_impl.hpp