Slick OrderBook: slick::orderbook::detail::OrderMap Class Reference
slick::orderbook::detail::OrderMap Class Reference
Hash table for fast OrderId -> Order* lookup Uses std::unordered_map for simplicity and performance Provides O(1) average-case lookup, insertion, and deletion.
#include <order_map.hpp>
Public Types
using MapType = std::unordered_map< OrderId, Order * >
using iterator = MapType::iterator
using const_iterator = MapType::const_iterator
Public Member Functions
OrderMap (std::size_t initial_capacity=1024)
Constructor with initial capacity.
bool insert (Order *order) noexcept
Insert order into map.
bool erase (OrderId order_id) noexcept
Remove order from map.
Order * find (OrderId order_id) noexcept
Find order by OrderId.
const Order * find (OrderId order_id) const noexcept
bool contains (OrderId order_id) const noexcept
Check if order exists.
std::size_t size () const noexcept
Get number of orders in map.
bool empty () const noexcept
Check if map is empty.
void reserve (std::size_t capacity)
Reserve capacity for orders.
void clear () noexcept
Clear all orders.
iterator begin () noexcept
Iterators.
iterator end () noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
Detailed Description
Hash table for fast OrderId -> Order* lookup Uses std::unordered_map for simplicity and performance Provides O(1) average-case lookup, insertion, and deletion.
Definition at line 16 of file order_map.hpp.
Member Typedef Documentation
const_iterator
using slick::orderbook::detail::OrderMap::const_iterator = MapType::const_iterator
Definition at line 20 of file order_map.hpp.
iterator
using slick::orderbook::detail::OrderMap::iterator = MapType::iterator
Definition at line 19 of file order_map.hpp.
MapType
using slick::orderbook::detail::OrderMap::MapType = std::unordered_map<OrderId, Order*>
Definition at line 18 of file order_map.hpp.
Constructor & Destructor Documentation
OrderMap()
slick::orderbook::detail::OrderMap::OrderMap (std::size_t initial_capacity = 1024) inline explicit
Constructor with initial capacity.
Definition at line 23 of file order_map.hpp.
Member Function Documentation
begin() [1/2]
const_iterator slick::orderbook::detail::OrderMap::begin () const inline noexcept
Definition at line 84 of file order_map.hpp.
begin() [2/2]
iterator slick::orderbook::detail::OrderMap::begin () inline noexcept
Iterators.
Definition at line 82 of file order_map.hpp.
cbegin()
const_iterator slick::orderbook::detail::OrderMap::cbegin () const inline noexcept
Definition at line 86 of file order_map.hpp.
cend()
const_iterator slick::orderbook::detail::OrderMap::cend () const inline noexcept
Definition at line 87 of file order_map.hpp.
clear()
void slick::orderbook::detail::OrderMap::clear () inline noexcept
Clear all orders.
Definition at line 77 of file order_map.hpp.
contains()
bool slick::orderbook::detail::OrderMap::contains (OrderId order_id) const inline noexcept
Check if order exists.
Definition at line 57 of file order_map.hpp.
Referenced by slick::orderbook::OrderBookL3::addOrder().
empty()
bool slick::orderbook::detail::OrderMap::empty () const inline noexcept
Check if map is empty.
Definition at line 67 of file order_map.hpp.
end() [1/2]
const_iterator slick::orderbook::detail::OrderMap::end () const inline noexcept
Definition at line 85 of file order_map.hpp.
end() [2/2]
iterator slick::orderbook::detail::OrderMap::end () inline noexcept
Definition at line 83 of file order_map.hpp.
erase()
bool slick::orderbook::detail::OrderMap::erase (OrderId order_id) inline noexcept
Remove order from map.
Parameters
order_id OrderId to remove
Returns
true if order was found and removed
Definition at line 39 of file order_map.hpp.
find() [1/2]
const Order * slick::orderbook::detail::OrderMap::find (OrderId order_id) const inline noexcept
Definition at line 51 of file order_map.hpp.
find() [2/2]
Order * slick::orderbook::detail::OrderMap::find (OrderId order_id) inline noexcept
Find order by OrderId.
Parameters
order_id OrderId to find
Returns
Pointer to order, or nullptr if not found
Definition at line 46 of file order_map.hpp.
Referenced by slick::orderbook::OrderBookL3::addOrModifyOrder(), slick::orderbook::OrderBookL3::executeOrder(), and slick::orderbook::OrderBookL3::modifyOrder().
insert()
bool slick::orderbook::detail::OrderMap::insert (Order * order) inline noexcept
Insert order into map.
Parameters
order Pointer to order (must not be null)
Returns
true if insertion succeeded, false if OrderId already exists
Definition at line 30 of file order_map.hpp.
References SLICK_ASSERT.
Referenced by slick::orderbook::OrderBookL3::addOrModifyOrder().
reserve()
void slick::orderbook::detail::OrderMap::reserve (std::size_t capacity) inline
Reserve capacity for orders.
Definition at line 72 of file order_map.hpp.
size()
std::size_t slick::orderbook::detail::OrderMap::size () const inline noexcept
Get number of orders in map.
Definition at line 62 of file order_map.hpp.
The documentation for this class was generated from the following file:
slick/orderbook/detail/order_map.hpp