Slick OrderBook: slick::orderbook::OrderBookL3 Class Reference
slick::orderbook::OrderBookL3 Class Reference
Level 3 OrderBook - Individual order tracking with price-time priority.
#include <orderbook_l3.hpp>
Classes
struct PriceComparator
Public Types
using PriceLevelMap = detail::FlatMap< Price, detail::PriceLevelL3, PriceComparator >
Public Member Functions
OrderBookL3 (SymbolId symbol, std::size_t initial_order_capacity=1024, std::size_t initial_level_capacity=32)
Constructor.
virtual ~OrderBookL3 ()
Destructor.
OrderBookL3 (const OrderBookL3 &)=delete
OrderBookL3 & operator= (const OrderBookL3 &)=delete
OrderBookL3 (OrderBookL3 &&) noexcept=default
OrderBookL3 & operator= (OrderBookL3 &&) noexcept=default
SymbolId symbol () const noexcept
Get symbol ID.
bool addOrModifyOrder (OrderId order_id, Side side, Price price, Quantity quantity, Timestamp timestamp, uint64_t priority, uint64_t seq_num=0, bool is_last_in_batch=true)
Add a new order or modify existing order if OrderId already exists If the order already exists, modifies its price and/or quantity.
bool addOrder (OrderId order_id, Side side, Price price, Quantity quantity, Timestamp timestamp, uint64_t priority=0, uint64_t seq_num=0, bool is_last_in_batch=true)
Add a new order (strict - fails if order already exists)
bool modifyOrder (OrderId order_id, Price new_price, Quantity new_quantity, Timestamp new_timestamp, uint64_t new_priority=0, uint64_t seq_num=0, bool is_last_in_batch=true)
Modify an existing order's price and/or quantity Compares new values with old to determine what changed.
bool deleteOrder (OrderId order_id, Timestamp timestamp, uint64_t seq_num=0, bool is_last_in_batch=true) noexcept
Delete an order.
bool executeOrder (OrderId order_id, Quantity executed_quantity, uint64_t seq_num=0, bool is_last_in_batch=true)
Execute (partially fill) an order.
const detail::Order * findOrder (OrderId order_id) const noexcept
Find order by OrderId.
const detail::PriceLevelL3 * getBestBid () const noexcept
Get best bid (highest buy price)
const detail::PriceLevelL3 * getBestAsk () const noexcept
Get best ask (lowest sell price)
TopOfBook getTopOfBook () const noexcept
Get top-of-book snapshot (aggregated L2 view)
const PriceLevelMap & getLevelsL3 (Side side) const noexcept
Get L3 price levels for a side (zero-copy access to full order data) Returns reference to flat_map, iterate with range-for.
std::vector< detail::PriceLevelL2 > getLevelsL2 (Side side, std::size_t depth=0) const
Get aggregated L2 price levels for a side Converts L3 data to L2 by aggregating quantities at each price.
std::pair< const detail::PriceLevelL3 *, uint16_t > getLevel (Side side, Price price) const noexcept
Get L3 price level by price Access the orders at this price via level->orders (IntrusiveList)
std::pair< detail::PriceLevelL3 *, uint16_t > getLevel (Side side, Price price) noexcept
const detail::PriceLevelL3 * getLevelByIndex (Side side, uint16_t index) const noexcept
Get L3 price level by index (0 = best)
std::size_t levelCount (Side side) const noexcept
Get number of price levels on a side.
std::size_t orderCount () const noexcept
Get total number of orders.
std::size_t orderCount (Side side) const noexcept
Get number of orders on a side.
bool isEmpty (Side side) const noexcept
Check if a side is empty.
bool isEmpty () const noexcept
Check if book is empty (both sides)
void clearSide (Side side) noexcept
Clear all orders on one side.
void clear () noexcept
Clear all orders (both sides)
void addObserver (std::shared_ptr< IOrderBookObserver > observer)
Observer management.
bool removeObserver (const std::shared_ptr< IOrderBookObserver > &observer)
void clearObservers () noexcept
std::size_t observerCount () const noexcept
uint64_t getLastSeqNum () const noexcept
Get last processed sequence number.
void emitSnapshot (Timestamp timestamp)
Emit complete orderbook snapshot to observers (L3 MBO) Useful for replaying full book state to a new observer Calls onSnapshotBegin(), followed by onOrderUpdate() for each order, then onSnapshotEnd()
Protected Member Functions
std::tuple< detail::PriceLevelL3 *, uint16_t, bool > getOrCreateLevel (Side side, Price price)
Get or create price level, returns pointer, index and if new level created.
bool removeLevelIfEmpty (Side side, Price price) noexcept
Remove price level if empty.
void notifyOrderUpdate (const detail::Order *order, Quantity old_quantity, Price old_price, Timestamp timestamp, uint16_t level_index, uint8_t change_flags, uint64_t seq_num) const
Notify observers of order update with level index and change flags.
void notifyOrderDelete (const detail::Order *order, Timestamp timestamp, uint16_t level_index, uint8_t change_flags, uint64_t seq_num) const
Notify observers of order delete with level index.
uint16_t calculateLevelIndex (Side side, Price price) const noexcept
Calculate price level index for a given side and price.
void notifyTrade (OrderId passive_order_id, OrderId aggressive_order_id, Side aggressor_side, Price price, Quantity quantity, Timestamp timestamp) const
Notify observers of trade.
void notifyPriceLevelUpdate (Side side, Price price, Quantity total_quantity, Timestamp timestamp, uint16_t level_index, uint8_t change_flags, uint64_t seq_num) const
Notify observers of price level update (L2 aggregated view)
void notifyTopOfBookIfChanged (Timestamp timestamp)
Notify observers of top-of-book update if best changed Updates cached_tob_ after notification.
Protected Attributes
SymbolId symbol_
std::array< PriceLevelMap, SideCount > levels_
detail::OrderMap order_map_
detail::ObjectPool< detail::Order > order_pool_
ObserverManager observers_
TopOfBook cached_tob_
uint64_t last_seq_num_
uint16_t change_starting_index_ = INVALID_INDEX
Detailed Description
Level 3 OrderBook - Individual order tracking with price-time priority.
Maintains full order-by-order state with individual order visibility. Provides automatic aggregated L2 view.
Features:
O(1) order lookup by OrderId
O(log n) price level operations
Priority-based order queuing at each price level
Automatic L2 aggregation from L3 data
Observer pattern for notifications
Zero-allocation order management via object pool
Thread Safety: Single writer, multiple readers (lock-free reads planned)
Memory Layout: Cache-aligned to 64 bytes for optimal performance
Usage:
OrderBookL3 book(symbol_id);
book.addOrder(order_id, Side::Buy, 10000, 100, timestamp, priority);
book.modifyOrder(order_id, 10100, 150); // Update price and quantity
// Iterate L3 levels (zero-copy)
for (const auto& [price, level] : book.getLevelsL3(Side::Buy)) {
    for (const auto& order : level.orders) {
        // Process individual order...
    }
}
// Get aggregated L2 view
auto l2_levels = book.getLevelsL2(Side::Buy, 10); // Top 10 levels
book.deleteOrder(order_id);
Definition at line 61 of file orderbook_l3.hpp.
Member Typedef Documentation
PriceLevelMap
using slick::orderbook::OrderBookL3::PriceLevelMap = detail::FlatMap<Price, detail::PriceLevelL3, PriceComparator>
Definition at line 80 of file orderbook_l3.hpp.
Constructor & Destructor Documentation
OrderBookL3() [1/3]
slick::orderbook::OrderBookL3::OrderBookL3 (SymbolId symbol, std::size_t initial_order_capacity = 1024, std::size_t initial_level_capacity = 32) inline explicit
Constructor.
Parameters
symbol Symbol identifier
initial_order_capacity Initial capacity for order pool
initial_level_capacity Initial capacity for price levels per side
Definition at line 14 of file orderbook_l3_impl.hpp.
References slick::orderbook::Buy, cached_tob_, levels_, slick::orderbook::Sell, slick::orderbook::TopOfBook::symbol, and symbol_.
~OrderBookL3()
slick::orderbook::OrderBookL3::~OrderBookL3 () inline virtual
Destructor.
Definition at line 35 of file orderbook_l3_impl.hpp.
References clear().
OrderBookL3() [2/3]
slick::orderbook::OrderBookL3::OrderBookL3 (const OrderBookL3 &) delete
OrderBookL3() [3/3]
slick::orderbook::OrderBookL3::OrderBookL3 (OrderBookL3 &&) default noexcept
Member Function Documentation
addObserver()
void slick::orderbook::OrderBookL3::addObserver (std::shared_ptr< IOrderBookObserver > observer) inline
Observer management.
Definition at line 251 of file orderbook_l3.hpp.
addOrder()
bool slick::orderbook::OrderBookL3::addOrder (OrderId order_id, Side side, Price price, Quantity quantity, Timestamp timestamp, uint64_t priority = 0, uint64_t seq_num = 0, bool is_last_in_batch = true) inline
Add a new order (strict - fails if order already exists)
Parameters
order_id Unique order identifier
side Buy or Sell
price Order price
quantity Order quantity
timestamp Order timestamp
priority Priority for sorting (defaults to timestamp)
seq_num Exchange sequence number (0 = no tracking, default) Out-of-order updates (seq_num < last_seq_num) are rejected
is_last_in_batch Set to true if this is the last update in an external batch (enables batching of TopOfBook updates)
Returns
true if order was added successfully, false if OrderId already exists
Definition at line 120 of file orderbook_l3_impl.hpp.
References addOrModifyOrder(), slick::orderbook::detail::OrderMap::contains(), last_seq_num_, and order_map_.
addOrModifyOrder()
bool slick::orderbook::OrderBookL3::addOrModifyOrder (OrderId order_id, Side side, Price price, Quantity quantity, Timestamp timestamp, uint64_t priority, uint64_t seq_num = 0, bool is_last_in_batch = true) inline
Add a new order or modify existing order if OrderId already exists If the order already exists, modifies its price and/or quantity.
Parameters
order_id Unique order identifier
side Buy or Sell (must match existing order's side if it exists)
price Order price
quantity Order quantity
timestamp Order timestamp
priority Priority for sorting (used only when adding new order)
seq_num Exchange sequence number (0 = no tracking, default) Out-of-order updates (seq_num < last_seq_num) are rejected
is_last_in_batch Set to true if this is the last update in an external batch (enables batching of TopOfBook updates)
Returns
true if order was added or modified successfully
Definition at line 40 of file orderbook_l3_impl.hpp.
References change_starting_index_, deleteOrder(), slick::orderbook::detail::OrderMap::find(), getOrCreateLevel(), slick::orderbook::detail::OrderMap::insert(), slick::orderbook::INVALID_INDEX, last_seq_num_, slick::orderbook::LastInBatch, modifyOrder(), notifyOrderUpdate(), notifyPriceLevelUpdate(), notifyTopOfBookIfChanged(), order_map_, order_pool_, slick::orderbook::detail::Order::price, slick::orderbook::PriceChanged, slick::orderbook::detail::Order::priority, slick::orderbook::detail::Order::quantity, slick::orderbook::QuantityChanged, slick::orderbook::detail::Order::side, slick::orderbook::SideCount, SLICK_ASSERT, and SLICK_UNLIKELY.
Referenced by addOrder().
calculateLevelIndex()
uint16_t slick::orderbook::OrderBookL3::calculateLevelIndex (Side side, Price price) const inline protected noexcept
Calculate price level index for a given side and price.
Definition at line 589 of file orderbook_l3_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
clear()
void slick::orderbook::OrderBookL3::clear () inline noexcept
Clear all orders (both sides)
Definition at line 553 of file orderbook_l3_impl.hpp.
References slick::orderbook::Buy, clearSide(), and slick::orderbook::Sell.
Referenced by ~OrderBookL3().
clearObservers()
void slick::orderbook::OrderBookL3::clearObservers () inline noexcept
Definition at line 259 of file orderbook_l3.hpp.
clearSide()
void slick::orderbook::OrderBookL3::clearSide (Side side) inline noexcept
Clear all orders on one side.
Parameters
side Buy or Sell
Definition at line 534 of file orderbook_l3_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
Referenced by clear().
deleteOrder()
bool slick::orderbook::OrderBookL3::deleteOrder (OrderId order_id, Timestamp timestamp, uint64_t seq_num = 0, bool is_last_in_batch = true) inline noexcept
Delete an order.
Parameters
order_id Order identifier
timestamp Timestamp of the deletion (required)
seq_num Exchange sequence number (0 = no tracking, default) Out-of-order updates (seq_num < last_seq_num) are rejected
is_last_in_batch Set to true if this is the last update in an external batch (enables batching of TopOfBook updates)
Returns
true if order was found and deleted
Definition at line 285 of file orderbook_l3_impl.hpp.
References slick::orderbook::INVALID_INDEX, slick::orderbook::LastInBatch, slick::orderbook::detail::Order::price, slick::orderbook::PriceChanged, slick::orderbook::QuantityChanged, slick::orderbook::detail::Order::side, and slick::orderbook::detail::Order::timestamp.
Referenced by addOrModifyOrder(), executeOrder(), and modifyOrder().
emitSnapshot()
void slick::orderbook::OrderBookL3::emitSnapshot (Timestamp timestamp) inline
Emit complete orderbook snapshot to observers (L3 MBO) Useful for replaying full book state to a new observer Calls onSnapshotBegin(), followed by onOrderUpdate() for each order, then onSnapshotEnd()
Parameters
timestamp Snapshot timestamp
Definition at line 699 of file orderbook_l3_impl.hpp.
References slick::orderbook::Buy, last_seq_num_, levels_, slick::orderbook::ObserverManager::notifyOrderUpdate(), slick::orderbook::ObserverManager::notifySnapshotBegin(), slick::orderbook::ObserverManager::notifySnapshotEnd(), observers_, slick::orderbook::OrderUpdate::order_id, slick::orderbook::PriceChanged, slick::orderbook::QuantityChanged, slick::orderbook::Sell, and symbol_.
executeOrder()
bool slick::orderbook::OrderBookL3::executeOrder (OrderId order_id, Quantity executed_quantity, uint64_t seq_num = 0, bool is_last_in_batch = true) inline
Execute (partially fill) an order.
Parameters
order_id Order identifier
executed_quantity Quantity executed
seq_num Exchange sequence number (0 = no tracking, default) Out-of-order updates (seq_num < last_seq_num) are rejected
is_last_in_batch Set to true if this is the last update in an external batch (enables batching of TopOfBook updates)
Returns
true if order was found and executed
Definition at line 358 of file orderbook_l3_impl.hpp.
References deleteOrder(), slick::orderbook::detail::OrderMap::find(), last_seq_num_, modifyOrder(), order_map_, slick::orderbook::detail::Order::price, slick::orderbook::detail::Order::priority, slick::orderbook::detail::Order::quantity, SLICK_ASSERT, SLICK_UNLIKELY, and slick::orderbook::detail::Order::timestamp.
findOrder()
const detail::Order * slick::orderbook::OrderBookL3::findOrder (OrderId order_id) const inline noexcept
Find order by OrderId.
Parameters
order_id Order identifier
Returns
Pointer to order, or nullptr if not found
Definition at line 392 of file orderbook_l3_impl.hpp.
getBestAsk()
const detail::PriceLevelL3 * slick::orderbook::OrderBookL3::getBestAsk () const inline noexcept
Get best ask (lowest sell price)
Returns
Pointer to best ask level, or nullptr if no asks
Definition at line 406 of file orderbook_l3_impl.hpp.
References levels_, and slick::orderbook::Sell.
Referenced by getTopOfBook(), and notifyTopOfBookIfChanged().
getBestBid()
const detail::PriceLevelL3 * slick::orderbook::OrderBookL3::getBestBid () const inline noexcept
Get best bid (highest buy price)
Returns
Pointer to best bid level, or nullptr if no bids
Definition at line 396 of file orderbook_l3_impl.hpp.
References slick::orderbook::Buy, and levels_.
Referenced by getTopOfBook(), and notifyTopOfBookIfChanged().
getLastSeqNum()
uint64_t slick::orderbook::OrderBookL3::getLastSeqNum () const inline noexcept
Get last processed sequence number.
Returns
Last sequence number (0 if not tracking)
Definition at line 269 of file orderbook_l3.hpp.
getLevel() [1/2]
std::pair< const detail::PriceLevelL3 *, uint16_t > slick::orderbook::OrderBookL3::getLevel (Side side, Price price) const inline noexcept
Get L3 price level by price Access the orders at this price via level->orders (IntrusiveList)
Parameters
side Buy or Sell
price Price level
Returns
Pair of pointer to L3 price level (or nullptr if not found) and level index
Definition at line 478 of file orderbook_l3_impl.hpp.
References slick::orderbook::INVALID_INDEX, slick::orderbook::SideCount, and SLICK_ASSERT.
Referenced by modifyOrder().
getLevel() [2/2]
std::pair< detail::PriceLevelL3 *, uint16_t > slick::orderbook::OrderBookL3::getLevel (Side side, Price price) inline noexcept
Definition at line 489 of file orderbook_l3_impl.hpp.
References slick::orderbook::INVALID_INDEX, slick::orderbook::SideCount, and SLICK_ASSERT.
getLevelByIndex()
const detail::PriceLevelL3 * slick::orderbook::OrderBookL3::getLevelByIndex (Side side, uint16_t index) const inline noexcept
Get L3 price level by index (0 = best)
Parameters
side Buy or Sell
index Level index (0-based, 0 = best bid/ask)
Returns
Pointer to L3 price level, or nullptr if index out of range
Definition at line 500 of file orderbook_l3_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
getLevelsL2()
std::vector< detail::PriceLevelL2 > slick::orderbook::OrderBookL3::getLevelsL2 (Side side, std::size_t depth = 0) const inline
Get aggregated L2 price levels for a side Converts L3 data to L2 by aggregating quantities at each price.
Parameters
side Buy or Sell
depth Maximum number of levels (0 = all)
Returns
Vector of aggregated L2 price levels
Definition at line 444 of file orderbook_l3_impl.hpp.
References slick::orderbook::Buy, levels_, slick::orderbook::SideCount, and SLICK_ASSERT.
getLevelsL3()
const PriceLevelMap & slick::orderbook::OrderBookL3::getLevelsL3 (Side side) const inline noexcept
Get L3 price levels for a side (zero-copy access to full order data) Returns reference to flat_map, iterate with range-for.
Parameters
side Buy or Sell
Returns
Reference to L3 price level map
Definition at line 193 of file orderbook_l3.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
getOrCreateLevel()
std::tuple< detail::PriceLevelL3 *, uint16_t, bool > slick::orderbook::OrderBookL3::getOrCreateLevel (Side side, Price price) inline protected
Get or create price level, returns pointer, index and if new level created.
Definition at line 558 of file orderbook_l3_impl.hpp.
References levels_, slick::orderbook::SideCount, and SLICK_ASSERT.
Referenced by addOrModifyOrder(), and modifyOrder().
getTopOfBook()
TopOfBook slick::orderbook::OrderBookL3::getTopOfBook () const inline noexcept
Get top-of-book snapshot (aggregated L2 view)
Returns
TopOfBook structure with best bid/ask
Definition at line 415 of file orderbook_l3_impl.hpp.
References slick::orderbook::TopOfBook::ask_quantity, slick::orderbook::TopOfBook::best_ask, slick::orderbook::TopOfBook::best_bid, slick::orderbook::TopOfBook::bid_quantity, getBestAsk(), getBestBid(), slick::orderbook::TopOfBook::symbol, symbol_, and slick::orderbook::TopOfBook::timestamp.
isEmpty() [1/2]
bool slick::orderbook::OrderBookL3::isEmpty () const inline noexcept
Check if book is empty (both sides)
Returns
true if both sides are empty
Definition at line 530 of file orderbook_l3_impl.hpp.
References slick::orderbook::Buy, levels_, and slick::orderbook::Sell.
isEmpty() [2/2]
bool slick::orderbook::OrderBookL3::isEmpty (Side side) const inline noexcept
Check if a side is empty.
Parameters
side Buy or Sell
Returns
true if side has no orders
Definition at line 525 of file orderbook_l3_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
levelCount()
std::size_t slick::orderbook::OrderBookL3::levelCount (Side side) const inline noexcept
Get number of price levels on a side.
Parameters
side Buy or Sell
Returns
Number of levels
Definition at line 511 of file orderbook_l3_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
modifyOrder()
bool slick::orderbook::OrderBookL3::modifyOrder (OrderId order_id, Price new_price, Quantity new_quantity, Timestamp new_timestamp, uint64_t new_priority = 0, uint64_t seq_num = 0, bool is_last_in_batch = true) inline
Modify an existing order's price and/or quantity Compares new values with old to determine what changed.
Parameters
order_id Order identifier
new_price New price
new_quantity New quantity (0 = delete)
new_timestamp Timestamp of the modification (required)
new_priority New priority (default: 0 = use new_timestamp as priority for FIFO ordering) Use non-zero to explicitly set queue position priority
seq_num Exchange sequence number (0 = no tracking, default) Out-of-order updates (seq_num < last_seq_num) are rejected
is_last_in_batch Set to true if this is the last update in an external batch (enables batching of TopOfBook updates)
Returns
true if order was found and modified
Definition at line 140 of file orderbook_l3_impl.hpp.
References change_starting_index_, deleteOrder(), slick::orderbook::detail::OrderMap::find(), getLevel(), getOrCreateLevel(), slick::orderbook::INVALID_INDEX, last_seq_num_, slick::orderbook::LastInBatch, notifyOrderUpdate(), notifyPriceLevelUpdate(), notifyTopOfBookIfChanged(), order_map_, slick::orderbook::detail::Order::price, slick::orderbook::PriceChanged, slick::orderbook::detail::Order::priority, slick::orderbook::detail::Order::quantity, slick::orderbook::QuantityChanged, removeLevelIfEmpty(), slick::orderbook::detail::Order::side, SLICK_UNLIKELY, and slick::orderbook::detail::Order::timestamp.
Referenced by addOrModifyOrder(), and executeOrder().
notifyOrderDelete()
void slick::orderbook::OrderBookL3::notifyOrderDelete (const detail::Order * order, Timestamp timestamp, uint16_t level_index, uint8_t change_flags, uint64_t seq_num) const inline protected
Notify observers of order delete with level index.
Definition at line 623 of file orderbook_l3_impl.hpp.
References slick::orderbook::ObserverManager::notifyOrderUpdate(), observers_, slick::orderbook::detail::Order::order_id, slick::orderbook::detail::Order::price, slick::orderbook::detail::Order::priority, slick::orderbook::detail::Order::side, and symbol_.
notifyOrderUpdate()
void slick::orderbook::OrderBookL3::notifyOrderUpdate (const detail::Order * order, Quantity old_quantity, Price old_price, Timestamp timestamp, uint16_t level_index, uint8_t change_flags, uint64_t seq_num) const inline protected
Notify observers of order update with level index and change flags.
Definition at line 605 of file orderbook_l3_impl.hpp.
References slick::orderbook::ObserverManager::notifyOrderUpdate(), observers_, slick::orderbook::detail::Order::order_id, slick::orderbook::detail::Order::price, slick::orderbook::detail::Order::priority, slick::orderbook::detail::Order::quantity, slick::orderbook::detail::Order::side, and symbol_.
Referenced by addOrModifyOrder(), and modifyOrder().
notifyPriceLevelUpdate()
void slick::orderbook::OrderBookL3::notifyPriceLevelUpdate (Side side, Price price, Quantity total_quantity, Timestamp timestamp, uint16_t level_index, uint8_t change_flags, uint64_t seq_num) const inline protected
Notify observers of price level update (L2 aggregated view)
Definition at line 654 of file orderbook_l3_impl.hpp.
References slick::orderbook::ObserverManager::notifyPriceLevelUpdate(), observers_, and symbol_.
Referenced by addOrModifyOrder(), and modifyOrder().
notifyTopOfBookIfChanged()
void slick::orderbook::OrderBookL3::notifyTopOfBookIfChanged (Timestamp timestamp) inline protected
Notify observers of top-of-book update if best changed Updates cached_tob_ after notification.
Parameters
timestamp Update timestamp
Definition at line 670 of file orderbook_l3_impl.hpp.
References slick::orderbook::TopOfBook::ask_quantity, slick::orderbook::TopOfBook::best_ask, slick::orderbook::TopOfBook::best_bid, slick::orderbook::TopOfBook::bid_quantity, cached_tob_, getBestAsk(), getBestBid(), slick::orderbook::ObserverManager::notifyTopOfBookUpdate(), observers_, and slick::orderbook::TopOfBook::timestamp.
Referenced by addOrModifyOrder(), and modifyOrder().
notifyTrade()
void slick::orderbook::OrderBookL3::notifyTrade (OrderId passive_order_id, OrderId aggressive_order_id, Side aggressor_side, Price price, Quantity quantity, Timestamp timestamp) const inline protected
Notify observers of trade.
Definition at line 639 of file orderbook_l3_impl.hpp.
References slick::orderbook::ObserverManager::notifyTrade(), observers_, and symbol_.
observerCount()
std::size_t slick::orderbook::OrderBookL3::observerCount () const inline noexcept
Definition at line 263 of file orderbook_l3.hpp.
operator=() [1/2]
OrderBookL3 & slick::orderbook::OrderBookL3::operator= (const OrderBookL3 &) delete
operator=() [2/2]
OrderBookL3 & slick::orderbook::OrderBookL3::operator= (OrderBookL3 &&) default noexcept
orderCount() [1/2]
std::size_t slick::orderbook::OrderBookL3::orderCount () const inline noexcept
Get total number of orders.
Returns
Total order count
Definition at line 227 of file orderbook_l3.hpp.
orderCount() [2/2]
std::size_t slick::orderbook::OrderBookL3::orderCount (Side side) const inline noexcept
Get number of orders on a side.
Parameters
side Buy or Sell
Returns
Number of orders on this side
Definition at line 516 of file orderbook_l3_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
removeLevelIfEmpty()
bool slick::orderbook::OrderBookL3::removeLevelIfEmpty (Side side, Price price) inline protected noexcept
Remove price level if empty.
Definition at line 576 of file orderbook_l3_impl.hpp.
References slick::orderbook::SideCount, and SLICK_ASSERT.
Referenced by modifyOrder().
removeObserver()
bool slick::orderbook::OrderBookL3::removeObserver (const std::shared_ptr< IOrderBookObserver > & observer) inline
Definition at line 255 of file orderbook_l3.hpp.
symbol()
SymbolId slick::orderbook::OrderBookL3::symbol () const inline noexcept
Get symbol ID.
Definition at line 100 of file orderbook_l3.hpp.
Member Data Documentation
cached_tob_
TopOfBook slick::orderbook::OrderBookL3::cached_tob_ protected
Definition at line 314 of file orderbook_l3.hpp.
Referenced by OrderBookL3(), and notifyTopOfBookIfChanged().
change_starting_index_
uint16_t slick::orderbook::OrderBookL3::change_starting_index_ = INVALID_INDEX protected
Definition at line 316 of file orderbook_l3.hpp.
Referenced by addOrModifyOrder(), and modifyOrder().
last_seq_num_
uint64_t slick::orderbook::OrderBookL3::last_seq_num_ protected
Definition at line 315 of file orderbook_l3.hpp.
Referenced by addOrder(), addOrModifyOrder(), emitSnapshot(), executeOrder(), and modifyOrder().
levels_
std::array<PriceLevelMap, SideCount> slick::orderbook::OrderBookL3::levels_ protected
Definition at line 310 of file orderbook_l3.hpp.
Referenced by OrderBookL3(), emitSnapshot(), getBestAsk(), getBestBid(), getLevelsL2(), getOrCreateLevel(), and isEmpty().
observers_
ObserverManager slick::orderbook::OrderBookL3::observers_ protected
Definition at line 313 of file orderbook_l3.hpp.
Referenced by emitSnapshot(), notifyOrderDelete(), notifyOrderUpdate(), notifyPriceLevelUpdate(), notifyTopOfBookIfChanged(), and notifyTrade().
order_map_
detail::OrderMap slick::orderbook::OrderBookL3::order_map_ protected
Definition at line 311 of file orderbook_l3.hpp.
Referenced by addOrder(), addOrModifyOrder(), executeOrder(), and modifyOrder().
order_pool_
detail::ObjectPool<detail::Order> slick::orderbook::OrderBookL3::order_pool_ protected
Definition at line 312 of file orderbook_l3.hpp.
Referenced by addOrModifyOrder().
symbol_
SymbolId slick::orderbook::OrderBookL3::symbol_ protected
Definition at line 309 of file orderbook_l3.hpp.
Referenced by OrderBookL3(), emitSnapshot(), getTopOfBook(), notifyOrderDelete(), notifyOrderUpdate(), notifyPriceLevelUpdate(), and notifyTrade().
The documentation for this class was generated from the following files:
slick/orderbook/orderbook_l3.hpp
slick/orderbook/detail/impl/orderbook_l3_impl.hpp