Slick OrderBook: slick::orderbook::detail::PriceLevelL3 Struct Reference
slick::orderbook::detail::PriceLevelL3 Struct Reference
Price level for Level 3 orderbook (order-by-order) Maintains a queue of individual orders at this price level.
#include <price_level_l3.hpp>
Public Member Functions
PriceLevelL3 (Price p) noexcept
Quantity getTotalQuantity () const noexcept
Get total quantity at this level.
std::size_t orderCount () const noexcept
Get number of orders at this level.
bool isEmpty () const noexcept
Check if this level is empty.
Order * getBestOrder () noexcept
Get best order (first in queue)
const Order * getBestOrder () const noexcept
void insertOrder (Order *order) noexcept
Insert order maintaining priority order.
void removeOrder (Order *order) noexcept
Remove order from the level.
void updateOrderQuantity (Quantity old_quantity, Quantity new_quantity) noexcept
Update order quantity (for modify operations)
constexpr bool operator== (const PriceLevelL3 &other) const noexcept
Comparison operators for sorting by price.
constexpr bool operator!= (const PriceLevelL3 &other) const noexcept
constexpr bool operator< (const PriceLevelL3 &other) const noexcept
constexpr bool operator> (const PriceLevelL3 &other) const noexcept
Public Attributes
Price price
IntrusiveList< Order > orders
Quantity total_quantity
Detailed Description
Price level for Level 3 orderbook (order-by-order) Maintains a queue of individual orders at this price level.
Definition at line 15 of file price_level_l3.hpp.
Constructor & Destructor Documentation
PriceLevelL3()
slick::orderbook::detail::PriceLevelL3::PriceLevelL3 (Price p) inline explicit noexcept
Definition at line 20 of file price_level_l3.hpp.
Member Function Documentation
getBestOrder() [1/2]
const Order * slick::orderbook::detail::PriceLevelL3::getBestOrder () const inline noexcept
Definition at line 43 of file price_level_l3.hpp.
References slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::empty(), and slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::front().
getBestOrder() [2/2]
Order * slick::orderbook::detail::PriceLevelL3::getBestOrder () inline noexcept
Get best order (first in queue)
Definition at line 39 of file price_level_l3.hpp.
References slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::empty(), and slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::front().
getTotalQuantity()
Quantity slick::orderbook::detail::PriceLevelL3::getTotalQuantity () const inline noexcept
Get total quantity at this level.
Definition at line 24 of file price_level_l3.hpp.
insertOrder()
void slick::orderbook::detail::PriceLevelL3::insertOrder (Order * order) inline noexcept
Insert order maintaining priority order.
Definition at line 48 of file price_level_l3.hpp.
References slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::begin(), slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::end(), slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::insert_before(), and slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::push_back().
isEmpty()
bool slick::orderbook::detail::PriceLevelL3::isEmpty () const inline noexcept
Check if this level is empty.
Definition at line 34 of file price_level_l3.hpp.
References slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::empty().
operator!=()
constexpr bool slick::orderbook::detail::PriceLevelL3::operator!= (const PriceLevelL3 & other) const inline constexpr noexcept
Definition at line 80 of file price_level_l3.hpp.
operator<()
constexpr bool slick::orderbook::detail::PriceLevelL3::operator< (const PriceLevelL3 & other) const inline constexpr noexcept
Definition at line 84 of file price_level_l3.hpp.
operator==()
constexpr bool slick::orderbook::detail::PriceLevelL3::operator== (const PriceLevelL3 & other) const inline constexpr noexcept
Comparison operators for sorting by price.
Definition at line 76 of file price_level_l3.hpp.
operator>()
constexpr bool slick::orderbook::detail::PriceLevelL3::operator> (const PriceLevelL3 & other) const inline constexpr noexcept
Definition at line 88 of file price_level_l3.hpp.
orderCount()
std::size_t slick::orderbook::detail::PriceLevelL3::orderCount () const inline noexcept
Get number of orders at this level.
Definition at line 29 of file price_level_l3.hpp.
References slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::size().
removeOrder()
void slick::orderbook::detail::PriceLevelL3::removeOrder (Order * order) inline noexcept
Remove order from the level.
Definition at line 65 of file price_level_l3.hpp.
References slick::orderbook::detail::IntrusiveList< T, NextPtr, PrevPtr >::erase().
updateOrderQuantity()
void slick::orderbook::detail::PriceLevelL3::updateOrderQuantity (Quantity old_quantity, Quantity new_quantity) inline noexcept
Update order quantity (for modify operations)
Definition at line 71 of file price_level_l3.hpp.
Member Data Documentation
orders
IntrusiveList<Order> slick::orderbook::detail::PriceLevelL3::orders
Definition at line 17 of file price_level_l3.hpp.
price
Price slick::orderbook::detail::PriceLevelL3::price
Definition at line 16 of file price_level_l3.hpp.
total_quantity
Quantity slick::orderbook::detail::PriceLevelL3::total_quantity
Definition at line 18 of file price_level_l3.hpp.
The documentation for this struct was generated from the following file:
slick/orderbook/detail/price_level_l3.hpp